<a href="https://colab.research.google.com/github/Amogha-Mayya/PyTorch-Practice/blob/main/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("CUDA is available")
  print(f"CUDA version: {torch.version.cuda}")
else:
  print("CUDA is not available")

CUDA is available
CUDA version: 12.8


### How to create a Tensor ?

In [ ]:
# using empty to create a tensor
torch.empty(2,3)

tensor([[1.6751e+04, 4.4046e-41, 1.6751e+04],
        [4.4046e-41, 2.2384e-07, 4.4046e-41]])

In [ ]:
# using zeros & ones to create a tensor
a = torch.zeros(2,3)
b = torch.ones(1,2)
print(a)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.]])


In [ ]:
# using rand to create a tensor
torch.rand(2,3)

tensor([[0.8388, 0.4459, 0.5367],
        [0.5972, 0.5003, 0.2394]])

In [ ]:
# manual seeding for REPRODUCIBILITY
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# torch tensor manually create a tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### Tensor Data Types ?

In [ ]:
x = torch.rand(2,3)

In [ ]:
x.shape   # shape of tensor
x.dtype   # dtype of tensor
x.to(torch.int32)     # change data type of tensor

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [ ]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### Mathematical Operations

In [ ]:
x = torch.rand(2,2)
print(x)
a = torch.rand(2,3)
b = torch.rand(3,1)

tensor([[0.1126, 0.1436],
        [0.7803, 0.5477]])


In [ ]:
# scalar operation
x + 2
x - 2
x / 2
x * 2
x ** 2

tensor([[0.0127, 0.0206],
        [0.6089, 0.3000]])

In [ ]:
# element wise
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [ ]:
# reduction operations
torch.sum(x)
torch.sum(x,axis = 1)
torch.mean(x)
torch.median(x)
torch.std(x)
torch.var(x)
torch.max(x)
torch.min(x)
torch.argmax(x)
torch.argmin(x)

tensor(2)

In [ ]:
# matrix operations
torch.matmul(a,b)
torch.transpose(a,0,1)
torch.det(x)
torch.dot(a,b)
torch.inverse(x)

tensor([[ 4.6572, -2.2551],
        [-9.2940,  7.5508]])

In [ ]:
# special functions
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
torch.log(k)
torch.exp(k)
torch.sqrt(k)
torch.sigmoid(k)
torch.softmax(k, dim=0)
torch.relu(k)

tensor([[3., 8., 9.],
        [3., 7., 8.]])

### Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])
tensor([[0.1816, 0.9998, 0.5944],
        [0.6541, 0.0337, 0.1716]])


In [ ]:
# to change any operator to inplace operation just add _ after the function name
m.relu_()
m.sigmoid_()
m.add_(n)

tensor([[0.3187, 1.5115, 0.7529],
        [0.7299, 0.2583, 0.2340]])

### Copy a Tensor

In [ ]:
b = a # shallow copy
b = a.clone() # deep copy
